export enum MarkerTypeEnum {
  Government = 'government',
  University = 'university',
  School = 'school',
  Hospital = 'hospital',
  Church = 'church',
  Castle = 'castle',
  Museum = 'museum',
  Park = 'park',
  Linden = 'linden',
  Sakura = 'sakura',
  Bridge = 'bridge',
  Square = 'square',
  Monument = 'monument',
  Market = 'market',
  Shopping = 'shopping',
  Restaurant = 'restaurant',
  Hotel = 'hotel',
  Stadium = 'stadium',
  Sports = 'sports',
  Library = 'library',
  Theater = 'theater',
}
